export const MaterialIconsEnum = {
  PersonAdd: 'person_add',
  MenuBook: 'menu_book',
  Pattern: 'pattern',
  Umbrella: 'umbrella',
  BarChart: 'bar_chart',
  Checklist: 'checklist',
  Groups: 'groups',
  Event: 'event',
  OpenInNew: 'open_in_new',
  CalendarMonth: 'calendar_month',
  SwapHoriz: 'swap_horiz',
  School: 'school',
  Assignment: 'assignment',
  Search: 'search',
  Help: 'help',
  OneTwoThree: '123',
  Badge: 'badge',
  Mood: 'mood',
  Schedule: 'schedule',
  Edit: 'edit',
  Work: 'work',
  Home: 'home',
  BusinessCenter: 'business_center',
  NotificaitonsOff: 'notifications_off',
  Close: 'close',
  ArrowBack: 'arrow_back',
  Menu: 'menu',
  Logout: 'logout',
  CloudUpload: 'cloud_upload',
  UploadFile: 'upload_file',
  Delete: 'delete',
  Add: 'add',
  Done: 'done',
  ToggleOn: 'toggle_on',
  ToggleOff: 'toggle_off',
  Visibility: 'visibility',
  VisibilityOff: 'visibility_off',
  EditOff: 'edit_off',
} as const;

export type MaterialIconKeys = keyof typeof MaterialIconsEnum;
export type MaterialIconValues = (typeof MaterialIconsEnum)[MaterialIconKeys];
